version: '3.3'

networks:
  internal:
    external: false

services:
  base:
    build: ./base
    image: mapcentia/gc2core:base8
  ecw:
    build: ./ecw
    image: mapcentia/gc2core:ecw8
    depends_on:
      - base
  gdal:
    build: ./gdal
    image: mapcentia/gc2core:gdal8
    depends_on:
      - ecw
  mapserver:
    build: ./mapserver
    image: mapcentia/gc2core:mapserver8
    depends_on:
      - gdal
  gc2core:
    build: ./stable
    image: mapcentia/gc2core8
    depends_on:
      - mapserver
    privileged: true
    volumes:
      - ../../geocloud2:/var/www/geocloud2
    networks:
      - default
      - internal
    ports:
      - "8080:80"
    expose:
      - 9000
    environment:
      - POSTGIS_HOST=postgis
      - POSTGIS_DB=postgres
      - POSTGIS_USER=gc2
      - POSTGIS_PORT=5432
      - POSTGIS_PW=1234
      - POSTGIS_PGBOUNCER=false
      - MODE_ENV=${MODE_ENV}
      - BUILD_ID=${BUILD_ID}
    extra_hosts:
      - host.docker.internal:host-gateway
  redis:
    image: redis
    networks:
      - default
      - internal
    ports:
      - "6379:6379"
  memcached:
    image: memcached
    networks:
      - default
      - internal
    ports:
      - "11211:11211"
  postgis:
    build: ./postgis
    image: mapcentia/postgis
    volumes:
      - postgis_var_lib_postgresql:/var/lib/postgresql
    networks:
      - default
      - internal
    ports:
      - "5432:5432"
    environment:
      - GC2_USER=gc2
      - GC2_PASSWORD=1234
#  elasticsearch:
#    image: elasticsearch:7.17.6
#    networks:
#      - default
#      - internal
#    ports:
#      - "9200:9200"
#    environment:
#      - "discovery.type=single-node"
#  zookeeper:
#    image: debezium/zookeeper:${DEBEZIUM_VERSION}
#    ports:
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
#    networks:
#      - internal
#  kafka:
#    image: debezium/kafka:${DEBEZIUM_VERSION}
#    ports:
#      - 9092:9092
#    environment:
#      - ZOOKEEPER_CONNECT=zookeeper:2181
#    networks:
#      - internal
#  connect:
#    image: debezium/connect:${DEBEZIUM_VERSION}
#    ports:
#      - 8083:8083
#    networks:
#      - internal
#    environment:
#      - BOOTSTRAP_SERVERS=kafka:9092
#      - GROUP_ID=1
#      - CONFIG_STORAGE_TOPIC=my_connect_configs
#      - OFFSET_STORAGE_TOPIC=my_connect_offsets
#      - STATUS_STORAGE_TOPIC=my_connect_statuses

volumes:
  postgis_var_lib_postgresql:





